### PR TITLE
Fix the use of instance doubles globally

### LINKED ISSUE #361: Switch to `instance_double` from `double`.
A global switch to `instance_double` for all uses of `double` is needed as the former form provides stronger guarantees.

### PR DESCRIPTION
**Pull request by mbj**
[fix #361]

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb Extraction from #486. Ready for review.

File: spec/unit/mutant/context_spec.rb [hunk 1]
```diff
@@ -31,27 +31,5 @@
 
       it { should eql(expected) }
     end
-
-    context 'with Class as scope' do
```
Comment (dkubb) [inline spec/unit/mutant/context_spec.rb]: Should these spec removals be broken up into a separate commit? I assume they were removed for some other reason?

File: spec/unit/mutant/integration/rspec_spec.rb [hunk 2]
```diff
@@ -115,10 +115,20 @@
...
+    expect(RSpec::Core::ConfigurationOptions).to receive(:new)
+      .with(%w[spec --fail-fast])
+      .and_return(rspec_options)
+
+    expect(RSpec::Core::Runner).to receive(:new)
+      .with(rspec_options)
+      .and_return(rspec_runner)
+
+    expect(RSpec).to receive(:world)
+      .with(no_args)
```
Comment (dkubb) [inline spec/unit/mutant/integration/rspec_spec.rb]: Can the `#world` method receive any arguments? If not, then I think specifying `with(no_args)` is redundant.

File: spec/unit/mutant/context_spec.rb (hunk 1 above)
Comment (mbj) [inline spec/unit/mutant/context_spec.rb]: Without this removal there is a un-reachable mutation covered branch in code that was selected via `--since` for this commit.

File: spec/unit/mutant/integration/rspec_spec.rb [hunk 3]
```diff
@@ -115,10 +115,20 @@
...
+      .and_return(world)
+
+    allow(Time).to receive(:now)
```
Comment (dkubb) [inline spec/unit/mutant/integration/rspec_spec.rb]: In situations where you are receiving and returning a value, the receive_messages method can sometimes be cleaner:

```ruby
allow(Time).to receive_messages(now: Time.now)
```

__NOTE:__ this may apply to other specs in this PR.

File: spec/unit/mutant/integration/rspec_spec.rb (hunk 2 above)
Comment (mbj) [inline spec/unit/mutant/integration/rspec_spec.rb]: Ohh, I thought its required else rspec would silenty throw away arguments.

File: spec/unit/mutant/integration/rspec_spec.rb (hunk 3 above)
Comment (mbj) [inline spec/unit/mutant/integration/rspec_spec.rb]: Will this assert `now` is called with zero arity?

File: spec/unit/mutant/integration/rspec_spec.rb (hunk 2 above)
Comment (dkubb) [inline spec/unit/mutant/integration/rspec_spec.rb]: No, it's mainly for use in methods that receive optional arguments and you want to specify the behaviour of the method when it receives nothing. I've overused it in the past too, and recently begun only asserting it in cases where a method takes optional args only.

Comment (mbj) [inline spec/unit/mutant/integration/rspec_spec.rb]: We need inverse mutation testing so we are forced to use the smallest possible set of semanics in the rspec API.

File: spec/unit/mutant/integration/rspec_spec.rb (hunk 3 above)
Comment (dkubb) [inline spec/unit/mutant/integration/rspec_spec.rb]: I don't think it asserts that `Time#now` is called with zero arity, but the method doesn't receive any arguments either. If some code actually attempted to pass an argument to the method it would result in a runtime exception.

IMHO, as mentioned above, it's not necessary to specify `with(...)` except in cases where the method could reasonably accept an argument.

Comment (mbj) [inline spec/unit/mutant/integration/rspec_spec.rb]: > If some code actually attempted to pass an argument to the method it would result in a runtime exception.

Thats what I wanted to know. Thx.

Comment (dkubb) [inline spec/unit/mutant/integration/rspec_spec.rb]: To further express my point, if we begin to asset a method does not receive arguments when it already cannot, then it's not really different than asserting that a method doesn't receive a block. Technically, I guess you could assert these things, but I think it's redundant.

**Comment by mbj** [comment]
@dkubb Ready for the next pass, flags addressed by code change or comment.
