### PR TITLE
Fix memoized method subjects to preserve freezer option

### LINKED ISSUE #639: Fix memoizable insertion to preserve freezer option
Mutant is right now configured to detect and re-produce memoized methods via the `memoziable` gem. In case the memoizable is used with `adamantium` the additional `freezer` option is currently silently dropped.

Resulting in an unintend behavior change observable in some noop failures. While certainly an interesting mutation, this mutation should be inserted explicitly, but not inside the noops.

### PR DESCRIPTION
**Pull request by snusnu**
Close #639

### CODE REVIEW

**Comment by snusnu** [comment]
@mbj Ready for review. I see CI is failing integration tests but I'm not sure if you need me to recurse into these.

**Comment by mbj** [comment]
@snusnu Code wise I'm fine, but the CI rusted. Hence it has to be fixed first.

File: spec/unit/mutant/subject/method/instance_spec.rb [hunk 1]
```diff
@@ -137,7 +153,7 @@ def foo; end
     it_should_behave_like 'a command method'
   end
 
-  describe '#mutations', mutant_expression: 'Mutant::Subject#mutations' do
+  describe '#mutations' do
```
Comment (mbj) [inline spec/unit/mutant/subject/method/instance_spec.rb:156]: @snusnu The fix for the last alive mutation was removing this overly specific overwrite!
